# Generated by Django 5.1.4 on 2024-12-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='id_ingredient',
            field=models.PositiveIntegerField(default=1, unique=True, verbose_name='id_ingredient'),
            preserve_default=False,
        ),
    ]
