# Generated by Django 5.1.4 on 2025-01-02 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedimage',
            name='title',
        ),
    ]
